/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/topics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list"];
        put?: never;
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_1"];
        put?: never;
        post: operations["create_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/nodes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["create_2"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/nodes/{nodeId}/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_2"];
        put?: never;
        post: operations["attach"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/nodes/{nodeId}/citations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["create_3"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/library/books": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_3"];
        put?: never;
        post: operations["create_4"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/edges": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["create_5"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/authorities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_4"];
        put?: never;
        post: operations["create_6"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/shamela/sync-master": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["syncMaster"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/shamela/map-book/{bookId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["mapBook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/shamela/import-book/{bookId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["importBook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/nodes/{nodeId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["delete"];
        options?: never;
        head?: never;
        patch: operations["update"];
        trace?: never;
    };
    "/api/v1/edges/{edgeId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["delete_1"];
        options?: never;
        head?: never;
        patch: operations["update_1"];
        trace?: never;
    };
    "/api/v1/topics/{topicId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getOne"];
        put?: never;
        post?: never;
        delete: operations["delete_2"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/topics/{topicId}/graph": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getGraph"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sources/{sourceId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getOne_1"];
        put?: never;
        post?: never;
        delete: operations["delete_3"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/nodes/{nodeId}/revisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getRevisions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/library/pages/{pageId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getPage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/library/books/{bookId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getOne_2"];
        put?: never;
        post?: never;
        delete: operations["delete_4"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/library/books/{bookId}/pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["streamPdf"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/library/books/{bookId}/pdf/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getPdfInfo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/library/books/{bookId}/pages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listPages"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/authorities/{authorityId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getOne_3"];
        put?: never;
        post?: never;
        delete: operations["delete_5"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/shamela/sync-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["syncStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/shamela/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["searchBooks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/nodes/{nodeId}/sources/{sourceId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["detach"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CreateTopicRequest: {
            title: string;
            description?: string;
            rootQuestion: string;
        };
        TopicResponse: {
            /** Format: uuid */
            id?: string;
            title?: string;
            description?: string;
            /** Format: uuid */
            rootNodeId?: string;
            /** Format: uuid */
            createdBy?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: int32 */
            nodeCount?: number;
            /** Format: int32 */
            edgeCount?: number;
        };
        CreateSourceRequest: {
            /** @enum {string} */
            sourceType: "QURAN" | "HADITH" | "BOOK" | "ARTICLE" | "URL";
            title: string;
            citation?: string;
            /** @enum {string} */
            reliability?: "SAHIH" | "HASAN" | "DAIF";
            /** Format: uuid */
            authorityId?: string;
            metadata?: components["schemas"]["JsonNode"];
        };
        JsonNode: Record<string, never>;
        SourceResponse: {
            /** Format: uuid */
            id?: string;
            /** @enum {string} */
            sourceType?: "QURAN" | "HADITH" | "BOOK" | "ARTICLE" | "URL";
            title?: string;
            citation?: string;
            /** @enum {string} */
            reliability?: "SAHIH" | "HASAN" | "DAIF";
            /** Format: uuid */
            authorityId?: string;
            /** Format: uuid */
            bookId?: string;
            metadata?: components["schemas"]["JsonNode"];
            /** Format: date-time */
            createdAt?: string;
        };
        CreateNodeRequest: {
            /** Format: uuid */
            topicId: string;
            /** @enum {string} */
            nodeType: "QUESTION" | "CLAIM" | "ARGUMENT" | "EVIDENCE";
            content: string;
        };
        NodeResponse: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            topicId?: string;
            /** @enum {string} */
            nodeType?: "QUESTION" | "CLAIM" | "ARGUMENT" | "EVIDENCE";
            content?: string;
            /** @enum {string} */
            status?: "STANDING" | "DISPUTED" | "REFUTED" | "UNVERIFIED";
            /** Format: double */
            posX?: number;
            /** Format: double */
            posY?: number;
            /** Format: uuid */
            createdBy?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        AttachSourceRequest: {
            /** Format: uuid */
            sourceId: string;
            quote?: string;
            context?: string;
            location?: string;
        };
        NodeSourceResponse: {
            /** Format: uuid */
            nodeId?: string;
            /** Format: uuid */
            sourceId?: string;
            quote?: string;
            context?: string;
            location?: string;
            /** @enum {string} */
            mode?: "TEXT" | "PDF" | "REGION" | "LEGACY";
            /** Format: uuid */
            pageId?: string;
            /** Format: int32 */
            rangeStart?: number;
            /** Format: int32 */
            rangeEnd?: number;
            /** Format: uuid */
            pdfFileId?: string;
            /** Format: int32 */
            pdfPageNumber?: number;
            pdfBbox?: components["schemas"]["JsonNode"];
            /** Format: uuid */
            imageRegionId?: string;
            /** Format: uuid */
            bookId?: string;
            /** Format: date-time */
            createdAt?: string;
        };
        CitationRequest: {
            /** Format: uuid */
            bookId: string;
            /** Format: uuid */
            pageId?: string;
            /** Format: int32 */
            rangeStart?: number;
            /** Format: int32 */
            rangeEnd?: number;
            /** Format: uuid */
            pdfFileId?: string;
            /** Format: int32 */
            pdfPageNumber?: number;
            pdfBbox?: components["schemas"]["PdfBbox"];
            /** Format: uuid */
            imageRegionId?: string;
            quote?: string;
            context?: string;
        };
        PdfBbox: {
            /** Format: double */
            x?: number;
            /** Format: double */
            y?: number;
            /** Format: double */
            width?: number;
            /** Format: double */
            height?: number;
        };
        CreateBookRequest: {
            /** @enum {string} */
            bookType: "QURAN" | "HADITH_COLLECTION" | "BOOK" | "ARTICLE" | "MANUSCRIPT";
            title: string;
            /** Format: uuid */
            authorityId?: string;
            language: string;
            description?: string;
            metadata?: components["schemas"]["JsonNode"];
        };
        BookResponse: {
            /** Format: uuid */
            id?: string;
            /** @enum {string} */
            bookType?: "QURAN" | "HADITH_COLLECTION" | "BOOK" | "ARTICLE" | "MANUSCRIPT";
            title?: string;
            /** Format: uuid */
            authorityId?: string;
            language?: string;
            description?: string;
            metadata?: components["schemas"]["JsonNode"];
            /** Format: uuid */
            createdBy?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        CreateEdgeRequest: {
            /** Format: uuid */
            fromNodeId: string;
            /** Format: uuid */
            toNodeId: string;
            /** @enum {string} */
            edgeType: "SUPPORTS" | "REFUTES" | "QUALIFIES" | "INVALIDATES" | "RESPONDS_TO";
            rationale?: string;
            sourceHandle?: string;
            targetHandle?: string;
        };
        EdgeResponse: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            fromNodeId?: string;
            /** Format: uuid */
            toNodeId?: string;
            /** @enum {string} */
            edgeType?: "SUPPORTS" | "REFUTES" | "QUALIFIES" | "INVALIDATES" | "RESPONDS_TO";
            rationale?: string;
            sourceHandle?: string;
            targetHandle?: string;
            /** Format: uuid */
            createdBy?: string;
            /** Format: date-time */
            createdAt?: string;
        };
        CreateAuthorityRequest: {
            name: string;
            bio?: string;
            era?: string;
            madhab?: string;
            metadata?: components["schemas"]["JsonNode"];
        };
        AuthorityResponse: {
            /** Format: uuid */
            id?: string;
            name?: string;
            bio?: string;
            era?: string;
            madhab?: string;
            metadata?: components["schemas"]["JsonNode"];
            /** Format: date-time */
            createdAt?: string;
        };
        SyncMasterResponse: {
            changed?: boolean;
            /** Format: int32 */
            previousVersion?: number;
            /** Format: int32 */
            currentVersion?: number;
            /** Format: int32 */
            categoriesCount?: number;
            /** Format: int32 */
            authorsCount?: number;
            /** Format: int32 */
            booksCount?: number;
        };
        MapBookResponse: {
            /** Format: uuid */
            bookId?: string;
            /** Format: int64 */
            shamelaBookId?: number;
            created?: boolean;
            /** Format: uuid */
            authorityId?: string;
            /** Format: int32 */
            chaptersCount?: number;
            /** Format: int32 */
            pagesCount?: number;
        };
        ImportBookResponse: {
            /** Format: int64 */
            bookId?: number;
            /** Format: int32 */
            majorRelease?: number;
            /** Format: int32 */
            pagesCount?: number;
            /** Format: int32 */
            titlesCount?: number;
        };
        UpdateNodeRequest: {
            content?: string;
            /** Format: double */
            posX?: number;
            /** Format: double */
            posY?: number;
        };
        UpdateEdgeRequest: {
            /** Format: uuid */
            fromNodeId?: string;
            /** Format: uuid */
            toNodeId?: string;
            /** @enum {string} */
            edgeType?: "SUPPORTS" | "REFUTES" | "QUALIFIES" | "INVALIDATES" | "RESPONDS_TO";
            rationale?: string;
            sourceHandle?: string;
            targetHandle?: string;
        };
        GraphResponse: {
            topic?: components["schemas"]["TopicResponse"];
            nodes?: components["schemas"]["NodeResponse"][];
            edges?: components["schemas"]["EdgeResponse"][];
        };
        RevisionResponse: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            nodeId?: string;
            contentBefore?: string;
            contentAfter?: string;
            /** Format: uuid */
            changedBy?: string;
            /** Format: date-time */
            changedAt?: string;
        };
        ImageRegionResponse: {
            /** Format: uuid */
            id?: string;
            /** Format: double */
            x?: number;
            /** Format: double */
            y?: number;
            /** Format: double */
            width?: number;
            /** Format: double */
            height?: number;
            extractedText?: string;
        };
        PageResponse: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            bookId?: string;
            /** Format: uuid */
            chapterId?: string;
            /** Format: int32 */
            pageNumber?: number;
            printedPage?: string;
            part?: string;
            /** Format: int32 */
            pdfPageNumber?: number;
            textContent?: string;
            imageUrl?: string;
            imageRegions?: components["schemas"]["ImageRegionResponse"][];
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        BookSummaryResponse: {
            /** Format: uuid */
            id?: string;
            /** @enum {string} */
            bookType?: "QURAN" | "HADITH_COLLECTION" | "BOOK" | "ARTICLE" | "MANUSCRIPT";
            title?: string;
            /** Format: uuid */
            authorityId?: string;
            language?: string;
            /** Format: date-time */
            createdAt?: string;
        };
        BookDetailResponse: {
            /** Format: uuid */
            id?: string;
            /** @enum {string} */
            bookType?: "QURAN" | "HADITH_COLLECTION" | "BOOK" | "ARTICLE" | "MANUSCRIPT";
            title?: string;
            /** Format: uuid */
            authorityId?: string;
            language?: string;
            description?: string;
            metadata?: components["schemas"]["JsonNode"];
            /** Format: uuid */
            createdBy?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            chapters?: components["schemas"]["ChapterResponse"][];
        };
        ChapterResponse: {
            /** Format: uuid */
            id?: string;
            title?: string;
            /** Format: int32 */
            orderIndex?: number;
            /** Format: uuid */
            parentChapterId?: string;
            /** Format: int32 */
            startPageNumber?: number;
        };
        StreamingResponseBody: Record<string, never>;
        PdfFileInfoResponse: {
            /** Format: int32 */
            index?: number;
            label?: string;
            isCover?: boolean;
            /** Format: int64 */
            sizeBytes?: number;
            /** Format: int32 */
            pageCount?: number;
        };
        PdfInfoResponse: {
            hasCover?: boolean;
            /** Format: int64 */
            totalSizeBytes?: number;
            files?: components["schemas"]["PdfFileInfoResponse"][];
        };
        PageSummaryResponse: {
            /** Format: uuid */
            id?: string;
            /** Format: int32 */
            pageNumber?: number;
            printedPage?: string;
            part?: string;
            /** Format: uuid */
            chapterId?: string;
            hasText?: boolean;
            hasImage?: boolean;
        };
        SyncStatusResponse: {
            /** Format: int32 */
            masterVersion?: number;
            /** Format: date-time */
            lastSyncedAt?: string;
            /** Format: int32 */
            categoriesCount?: number;
            /** Format: int32 */
            authorsCount?: number;
            /** Format: int32 */
            booksCount?: number;
            /** Format: int32 */
            mappedBooksCount?: number;
        };
        StagingBookSearchResponse: {
            /** Format: int64 */
            bookId?: number;
            name?: string;
            authorName?: string;
            /** Format: int32 */
            majorRelease?: number;
            isMapped?: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TopicResponse"][];
                };
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header: {
                /** @description UUID текущего пользователя (ADR-006, временно до Spring Security в Этапе 6) */
                "X-User-Id": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTopicRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TopicResponse"];
                };
            };
        };
    };
    list_1: {
        parameters: {
            query?: {
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SourceResponse"][];
                };
            };
        };
    };
    create_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSourceRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SourceResponse"];
                };
            };
        };
    };
    create_2: {
        parameters: {
            query?: never;
            header: {
                /** @description UUID текущего пользователя (ADR-006, временно до Spring Security в Этапе 6) */
                "X-User-Id": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateNodeRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["NodeResponse"];
                };
            };
        };
    };
    list_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                nodeId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["NodeSourceResponse"][];
                };
            };
        };
    };
    attach: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                nodeId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AttachSourceRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["NodeSourceResponse"];
                };
            };
        };
    };
    create_3: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                nodeId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CitationRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["NodeSourceResponse"];
                };
            };
        };
    };
    list_3: {
        parameters: {
            query?: {
                q?: string;
                type?: "QURAN" | "HADITH_COLLECTION" | "BOOK" | "ARTICLE" | "MANUSCRIPT";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BookSummaryResponse"][];
                };
            };
        };
    };
    create_4: {
        parameters: {
            query: {
                currentUserId: string;
            };
            header: {
                /** @description UUID текущего пользователя (ADR-006, временно до Spring Security в Этапе 6) */
                "X-User-Id": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateBookRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BookResponse"];
                };
            };
        };
    };
    create_5: {
        parameters: {
            query?: never;
            header: {
                /** @description UUID текущего пользователя (ADR-006, временно до Spring Security в Этапе 6) */
                "X-User-Id": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateEdgeRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["EdgeResponse"];
                };
            };
        };
    };
    list_4: {
        parameters: {
            query?: {
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AuthorityResponse"][];
                };
            };
        };
    };
    create_6: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAuthorityRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AuthorityResponse"];
                };
            };
        };
    };
    syncMaster: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SyncMasterResponse"];
                };
            };
        };
    };
    mapBook: {
        parameters: {
            query: {
                currentUserId: string;
            };
            header: {
                /** @description UUID текущего пользователя (ADR-006, временно до Spring Security в Этапе 6) */
                "X-User-Id": string;
            };
            path: {
                bookId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MapBookResponse"];
                };
            };
        };
    };
    importBook: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bookId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ImportBookResponse"];
                };
            };
        };
    };
    delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                nodeId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update: {
        parameters: {
            query?: never;
            header: {
                /** @description UUID текущего пользователя (ADR-006, временно до Spring Security в Этапе 6) */
                "X-User-Id": string;
            };
            path: {
                nodeId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateNodeRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["NodeResponse"];
                };
            };
        };
    };
    delete_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                edgeId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                edgeId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateEdgeRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["EdgeResponse"];
                };
            };
        };
    };
    getOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                topicId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TopicResponse"];
                };
            };
        };
    };
    delete_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                topicId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getGraph: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                topicId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["GraphResponse"];
                };
            };
        };
    };
    getOne_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sourceId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SourceResponse"];
                };
            };
        };
    };
    delete_3: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sourceId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getRevisions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                nodeId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RevisionResponse"][];
                };
            };
        };
    };
    getPage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pageId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageResponse"];
                };
            };
        };
    };
    getOne_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bookId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BookDetailResponse"];
                };
            };
        };
    };
    delete_4: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bookId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    streamPdf: {
        parameters: {
            query?: {
                fileIndex?: number;
            };
            header?: {
                Range?: string;
            };
            path: {
                bookId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["StreamingResponseBody"];
                };
            };
        };
    };
    getPdfInfo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bookId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PdfInfoResponse"];
                };
            };
        };
    };
    listPages: {
        parameters: {
            query?: {
                from?: number;
                to?: number;
            };
            header?: never;
            path: {
                bookId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageSummaryResponse"][];
                };
            };
        };
    };
    getOne_3: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                authorityId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AuthorityResponse"];
                };
            };
        };
    };
    delete_5: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                authorityId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    syncStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SyncStatusResponse"];
                };
            };
        };
    };
    searchBooks: {
        parameters: {
            query: {
                q: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["StagingBookSearchResponse"][];
                };
            };
        };
    };
    detach: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                nodeId: string;
                sourceId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
