/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/topics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list"];
        put?: never;
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/topics/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["importMultipart"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_1"];
        put?: never;
        post: operations["create_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/questions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_2"];
        put?: never;
        post: operations["create_2"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/questions/{questionId}/citations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["create_3"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/questions/{questionId}/answers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_3"];
        put?: never;
        post: operations["create_4"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/questions/{questionId}/accepted-answer/{answerId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["acceptAnswer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/nodes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["create_5"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/nodes/{nodeId}/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_4"];
        put?: never;
        post: operations["attach"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/nodes/{nodeId}/citations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["create_6"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/library/imports/file": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["uploadFile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/library/books": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_5"];
        put?: never;
        post: operations["create_7"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/edges": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["create_8"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/authorities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_6"];
        put?: never;
        post: operations["create_9"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/answers/{answerId}/citations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["create_10"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/shamela/sync-master": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["syncMaster"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/shamela/map-book/{bookId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["mapBook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/shamela/import-book/{bookId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["importBook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/shamela/backfill-bibliography": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["backfillBibliography"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/questions/{questionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getOne"];
        put?: never;
        post?: never;
        delete: operations["delete"];
        options?: never;
        head?: never;
        patch: operations["update"];
        trace?: never;
    };
    "/api/v1/nodes/{nodeId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["delete_1"];
        options?: never;
        head?: never;
        patch: operations["update_1"];
        trace?: never;
    };
    "/api/v1/library/books/{bookId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getOne_1"];
        put?: never;
        post?: never;
        delete: operations["delete_2"];
        options?: never;
        head?: never;
        patch: operations["update_2"];
        trace?: never;
    };
    "/api/v1/edges/{edgeId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["delete_3"];
        options?: never;
        head?: never;
        patch: operations["update_3"];
        trace?: never;
    };
    "/api/v1/answers/{answerId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["delete_4"];
        options?: never;
        head?: never;
        patch: operations["update_4"];
        trace?: never;
    };
    "/api/v1/topics/{topicId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getOne_2"];
        put?: never;
        post?: never;
        delete: operations["delete_5"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/topics/{topicId}/graph": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getGraph"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/topics/{topicId}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["export"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sources/{sourceId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getOne_3"];
        put?: never;
        post?: never;
        delete: operations["delete_6"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/questions/{questionId}/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_7"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/nodes/{nodeId}/revisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getRevisions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/library/publishers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["search"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/library/publication-places": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["search_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/library/pages/{pageId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getPage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/library/muhaqqiqs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["search_2"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/library/books/{bookId}/pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["streamPdf"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/library/books/{bookId}/pdf/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getPdfInfo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/library/books/{bookId}/pages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listPages"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/authorities/{authorityId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getOne_4"];
        put?: never;
        post?: never;
        delete: operations["delete_7"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/answers/{answerId}/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_8"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/shamela/sync-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["syncStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/shamela/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["searchBooks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/questions/{questionId}/sources/{questionSourceId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["detach"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/questions/{questionId}/accepted-answer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["revokeAcceptance"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/nodes/{nodeId}/sources/{nodeSourceId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["detach_1"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/answers/{answerId}/sources/{answerSourceId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["detach_2"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CreateTopicRequest: {
            title: string;
            description?: string;
            rootQuestion: string;
        };
        TopicResponse: {
            /** Format: uuid */
            id?: string;
            title?: string;
            description?: string;
            /** Format: uuid */
            rootNodeId?: string;
            /** Format: uuid */
            createdBy?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: int32 */
            nodeCount?: number;
            /** Format: int32 */
            edgeCount?: number;
        };
        TopicImportResponse: {
            /** Format: uuid */
            topicId?: string;
            /** Format: int32 */
            importedNodes?: number;
            /** Format: int32 */
            importedEdges?: number;
            /** Format: int32 */
            importedNodeSources?: number;
            /** Format: int32 */
            importedSources?: number;
            /** Format: int32 */
            importedAuthorities?: number;
            warnings?: string[];
        };
        AuthorityData: {
            /** Format: uuid */
            id?: string;
            name?: string;
            bio?: string;
            era?: string;
            madhab?: string;
            metadata?: string;
            /** Format: date-time */
            createdAt?: string;
            fullName?: string;
            /** Format: int32 */
            deathYearHijri?: number;
        };
        BookRef: {
            /** Format: uuid */
            id?: string;
            title?: string;
            /** Format: uuid */
            authorityId?: string;
        };
        EdgeData: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            fromNodeId?: string;
            /** Format: uuid */
            toNodeId?: string;
            edgeType?: string;
            rationale?: string;
            sourceHandle?: string;
            targetHandle?: string;
            /** Format: uuid */
            createdBy?: string;
            /** Format: date-time */
            createdAt?: string;
        };
        NodeData: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            topicId?: string;
            nodeType?: string;
            content?: string;
            status?: string;
            /** Format: double */
            posX?: number;
            /** Format: double */
            posY?: number;
            /** Format: uuid */
            createdBy?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        NodeSourceData: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            nodeId?: string;
            /** Format: uuid */
            sourceId?: string;
            quote?: string;
            context?: string;
            location?: string;
            /** Format: uuid */
            pageId?: string;
            /** Format: int32 */
            rangeStart?: number;
            /** Format: int32 */
            rangeEnd?: number;
            /** Format: uuid */
            pdfFileId?: string;
            /** Format: int32 */
            pdfPageNumber?: number;
            pdfBbox?: string;
            /** Format: uuid */
            imageRegionId?: string;
            /** Format: date-time */
            createdAt?: string;
        };
        SourceData: {
            /** Format: uuid */
            id?: string;
            sourceType?: string;
            title?: string;
            citation?: string;
            reliability?: string;
            /** Format: uuid */
            authorityId?: string;
            /** Format: uuid */
            bookId?: string;
            metadata?: string;
            /** Format: date-time */
            createdAt?: string;
        };
        TopicData: {
            /** Format: uuid */
            id?: string;
            title?: string;
            description?: string;
            /** Format: uuid */
            rootNodeId?: string;
            /** Format: uuid */
            createdBy?: string;
            /** Format: date-time */
            createdAt?: string;
        };
        TopicExportDto: {
            formatVersion?: string;
            /** Format: date-time */
            exportedAt?: string;
            topic?: components["schemas"]["TopicData"];
            nodes?: components["schemas"]["NodeData"][];
            edges?: components["schemas"]["EdgeData"][];
            nodeSources?: components["schemas"]["NodeSourceData"][];
            sources?: components["schemas"]["SourceData"][];
            authorities?: components["schemas"]["AuthorityData"][];
            books?: components["schemas"]["BookRef"][];
        };
        CreateSourceRequest: {
            /** @enum {string} */
            sourceType: "QURAN" | "HADITH" | "BOOK" | "ARTICLE" | "URL";
            title: string;
            citation?: string;
            /** @enum {string} */
            reliability?: "SAHIH" | "HASAN" | "DAIF";
            /** Format: uuid */
            authorityId?: string;
            /** Format: uuid */
            bookId?: string;
            metadata?: components["schemas"]["JsonNode"];
        };
        JsonNode: Record<string, never>;
        SourceResponse: {
            /** Format: uuid */
            id?: string;
            /** @enum {string} */
            sourceType?: "QURAN" | "HADITH" | "BOOK" | "ARTICLE" | "URL";
            title?: string;
            citation?: string;
            /** @enum {string} */
            reliability?: "SAHIH" | "HASAN" | "DAIF";
            /** Format: uuid */
            authorityId?: string;
            /** Format: uuid */
            bookId?: string;
            metadata?: components["schemas"]["JsonNode"];
            /** Format: date-time */
            createdAt?: string;
        };
        CreateQuestionRequest: {
            title: string;
            body?: string;
        };
        QuestionResponse: {
            /** Format: uuid */
            id?: string;
            title?: string;
            body?: string;
            /** @enum {string} */
            status?: "OPEN" | "ANSWERED" | "CLOSED";
            /** Format: uuid */
            askedBy?: string;
            /** Format: uuid */
            acceptedAnswerId?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        CitationRequest: {
            /** Format: uuid */
            bookId: string;
            /** Format: uuid */
            pageId?: string;
            /** Format: int32 */
            rangeStart?: number;
            /** Format: int32 */
            rangeEnd?: number;
            /** Format: uuid */
            pdfFileId?: string;
            /** Format: int32 */
            pdfPageNumber?: number;
            pdfBbox?: components["schemas"]["PdfBbox"];
            /** Format: uuid */
            imageRegionId?: string;
            quote?: string;
            context?: string;
        };
        PdfBbox: {
            /** Format: double */
            x?: number;
            /** Format: double */
            y?: number;
            /** Format: double */
            width?: number;
            /** Format: double */
            height?: number;
        };
        AuthorityCitationRef: {
            /** Format: uuid */
            id?: string;
            name?: string;
            fullName?: string;
            /** Format: int32 */
            deathYearHijri?: number;
        };
        BookCitationRef: {
            /** Format: uuid */
            id?: string;
            title?: string;
            language?: string;
            /** Format: int32 */
            editionNumber?: number;
            /** Format: int32 */
            publishedYearHijri?: number;
            /** Format: int32 */
            publishedYearGregorian?: number;
        };
        CitationResponse: {
            authority?: components["schemas"]["AuthorityCitationRef"];
            book?: components["schemas"]["BookCitationRef"];
            muhaqqiq?: components["schemas"]["MuhaqqiqRef"];
            publisher?: components["schemas"]["PublisherRef"];
            publicationPlace?: components["schemas"]["PublicationPlaceRef"];
            location?: components["schemas"]["LocationRef"];
            pdf?: components["schemas"]["PdfRef"];
            region?: components["schemas"]["RegionRef"];
        };
        LocationRef: {
            /** Format: uuid */
            pageId?: string;
            part?: string;
            printedPage?: string;
            /** Format: int32 */
            pageNumber?: number;
            /** Format: int32 */
            rangeStart?: number;
            /** Format: int32 */
            rangeEnd?: number;
        };
        MuhaqqiqRef: {
            /** Format: uuid */
            id?: string;
            name?: string;
            fullName?: string;
        };
        PdfRef: {
            /** Format: uuid */
            fileId?: string;
            /** Format: int32 */
            pageNumber?: number;
            bbox?: components["schemas"]["JsonNode"];
        };
        PublicationPlaceRef: {
            /** Format: uuid */
            id?: string;
            name?: string;
        };
        PublisherRef: {
            /** Format: uuid */
            id?: string;
            name?: string;
        };
        QuestionSourceResponse: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            questionId?: string;
            /** Format: uuid */
            sourceId?: string;
            quote?: string;
            context?: string;
            /** @enum {string} */
            mode?: "TEXT" | "PDF" | "REGION" | "LEGACY";
            citation?: components["schemas"]["CitationResponse"];
            /** Format: date-time */
            createdAt?: string;
        };
        RegionRef: {
            /** Format: uuid */
            id?: string;
            printedPage?: string;
            /** Format: int32 */
            pageNumber?: number;
        };
        CreateAnswerRequest: {
            body: string;
        };
        AnswerResponse: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            questionId?: string;
            body?: string;
            /** Format: uuid */
            authorId?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            accepted?: boolean;
        };
        CreateNodeRequest: {
            /** Format: uuid */
            topicId: string;
            /** @enum {string} */
            nodeType: "QUESTION" | "CLAIM" | "ARGUMENT" | "EVIDENCE";
            content: string;
        };
        NodeResponse: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            topicId?: string;
            /** @enum {string} */
            nodeType?: "QUESTION" | "CLAIM" | "ARGUMENT" | "EVIDENCE";
            content?: string;
            /** @enum {string} */
            status?: "STANDING" | "DISPUTED" | "REFUTED" | "UNVERIFIED";
            /** Format: double */
            posX?: number;
            /** Format: double */
            posY?: number;
            /** Format: uuid */
            createdBy?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        AttachSourceRequest: {
            /** Format: uuid */
            sourceId: string;
            quote?: string;
            context?: string;
            location?: string;
        };
        NodeSourceResponse: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            nodeId?: string;
            /** Format: uuid */
            sourceId?: string;
            quote?: string;
            context?: string;
            /** @enum {string} */
            mode?: "TEXT" | "PDF" | "REGION" | "LEGACY";
            citation?: components["schemas"]["CitationResponse"];
            legacySnapshot?: string;
            /** Format: date-time */
            createdAt?: string;
        };
        FileImportResponse: {
            /** Format: uuid */
            bookId?: string;
            /** Format: uuid */
            fileId?: string;
            /** Format: int32 */
            pageCount?: number;
            contentHash?: string;
            /** Format: int64 */
            sizeBytes?: number;
            bucket?: string;
            storageKey?: string;
        };
        CreateBookRequest: {
            /** @enum {string} */
            bookType: "QURAN" | "HADITH_COLLECTION" | "BOOK" | "ARTICLE" | "MANUSCRIPT";
            title: string;
            /** Format: uuid */
            authorityId?: string;
            language: string;
            description?: string;
            metadata?: components["schemas"]["JsonNode"];
            muhaqqiqName?: string;
            publisherName?: string;
            publicationPlaceName?: string;
            /** Format: int32 */
            editionNumber?: number;
            /** Format: int32 */
            publishedYearHijri?: number;
            /** Format: int32 */
            publishedYearGregorian?: number;
        };
        BookResponse: {
            /** Format: uuid */
            id?: string;
            /** @enum {string} */
            bookType?: "QURAN" | "HADITH_COLLECTION" | "BOOK" | "ARTICLE" | "MANUSCRIPT";
            title?: string;
            /** Format: uuid */
            authorityId?: string;
            language?: string;
            description?: string;
            metadata?: components["schemas"]["JsonNode"];
            /** Format: uuid */
            createdBy?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        CreateEdgeRequest: {
            /** Format: uuid */
            fromNodeId: string;
            /** Format: uuid */
            toNodeId: string;
            /** @enum {string} */
            edgeType: "SUPPORTS" | "REFUTES" | "QUALIFIES" | "INVALIDATES" | "RESPONDS_TO";
            rationale?: string;
            sourceHandle?: string;
            targetHandle?: string;
        };
        EdgeResponse: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            fromNodeId?: string;
            /** Format: uuid */
            toNodeId?: string;
            /** @enum {string} */
            edgeType?: "SUPPORTS" | "REFUTES" | "QUALIFIES" | "INVALIDATES" | "RESPONDS_TO";
            rationale?: string;
            sourceHandle?: string;
            targetHandle?: string;
            /** Format: uuid */
            createdBy?: string;
            /** Format: date-time */
            createdAt?: string;
        };
        CreateAuthorityRequest: {
            name: string;
            bio?: string;
            era?: string;
            madhab?: string;
            metadata?: components["schemas"]["JsonNode"];
        };
        AuthorityResponse: {
            /** Format: uuid */
            id?: string;
            name?: string;
            bio?: string;
            era?: string;
            madhab?: string;
            metadata?: components["schemas"]["JsonNode"];
            /** Format: date-time */
            createdAt?: string;
            fullName?: string;
            /** Format: int32 */
            deathYearHijri?: number;
        };
        AnswerSourceResponse: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            answerId?: string;
            /** Format: uuid */
            sourceId?: string;
            quote?: string;
            context?: string;
            /** @enum {string} */
            mode?: "TEXT" | "PDF" | "REGION" | "LEGACY";
            citation?: components["schemas"]["CitationResponse"];
            /** Format: date-time */
            createdAt?: string;
        };
        SyncMasterResponse: {
            changed?: boolean;
            /** Format: int32 */
            previousVersion?: number;
            /** Format: int32 */
            currentVersion?: number;
            /** Format: int32 */
            categoriesCount?: number;
            /** Format: int32 */
            authorsCount?: number;
            /** Format: int32 */
            booksCount?: number;
        };
        MapBookResponse: {
            /** Format: uuid */
            bookId?: string;
            /** Format: int64 */
            shamelaBookId?: number;
            created?: boolean;
            /** Format: uuid */
            authorityId?: string;
            /** Format: int32 */
            chaptersCount?: number;
            /** Format: int32 */
            pagesCount?: number;
        };
        ImportBookResponse: {
            /** Format: int64 */
            bookId?: number;
            /** Format: int32 */
            majorRelease?: number;
            /** Format: int32 */
            pagesCount?: number;
            /** Format: int32 */
            titlesCount?: number;
        };
        BackfillBibliographyResponse: {
            /** Format: int32 */
            scanned?: number;
            /** Format: int32 */
            updated?: number;
            /** Format: int32 */
            skipped?: number;
        };
        UpdateQuestionRequest: {
            title?: string;
            body?: string;
            /** @enum {string} */
            status?: "OPEN" | "ANSWERED" | "CLOSED";
        };
        UpdateNodeRequest: {
            content?: string;
            /** Format: double */
            posX?: number;
            /** Format: double */
            posY?: number;
        };
        UpdateBookRequest: {
            muhaqqiqName?: string;
            publisherName?: string;
            publicationPlaceName?: string;
            /** Format: int32 */
            editionNumber?: number;
            /** Format: int32 */
            publishedYearHijri?: number;
            /** Format: int32 */
            publishedYearGregorian?: number;
        };
        BookDetailResponse: {
            /** Format: uuid */
            id?: string;
            /** @enum {string} */
            bookType?: "QURAN" | "HADITH_COLLECTION" | "BOOK" | "ARTICLE" | "MANUSCRIPT";
            title?: string;
            /** Format: uuid */
            authorityId?: string;
            language?: string;
            description?: string;
            metadata?: components["schemas"]["JsonNode"];
            /** Format: uuid */
            createdBy?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            chapters?: components["schemas"]["ChapterResponse"][];
            /** Format: uuid */
            muhaqqiqId?: string;
            /** Format: uuid */
            publisherId?: string;
            /** Format: uuid */
            publicationPlaceId?: string;
            /** Format: int32 */
            editionNumber?: number;
            /** Format: int32 */
            publishedYearHijri?: number;
            /** Format: int32 */
            publishedYearGregorian?: number;
            authority?: components["schemas"]["AuthorityCitationRef"];
            muhaqqiq?: components["schemas"]["MuhaqqiqRef"];
            publisher?: components["schemas"]["PublisherRef"];
            publicationPlace?: components["schemas"]["PublicationPlaceRef"];
        };
        ChapterResponse: {
            /** Format: uuid */
            id?: string;
            title?: string;
            /** Format: int32 */
            orderIndex?: number;
            /** Format: uuid */
            parentChapterId?: string;
            /** Format: int32 */
            startPageNumber?: number;
        };
        UpdateEdgeRequest: {
            /** Format: uuid */
            fromNodeId?: string;
            /** Format: uuid */
            toNodeId?: string;
            /** @enum {string} */
            edgeType?: "SUPPORTS" | "REFUTES" | "QUALIFIES" | "INVALIDATES" | "RESPONDS_TO";
            rationale?: string;
            sourceHandle?: string;
            targetHandle?: string;
        };
        UpdateAnswerRequest: {
            body: string;
        };
        GraphResponse: {
            topic?: components["schemas"]["TopicResponse"];
            nodes?: components["schemas"]["NodeResponse"][];
            edges?: components["schemas"]["EdgeResponse"][];
        };
        RevisionResponse: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            nodeId?: string;
            contentBefore?: string;
            contentAfter?: string;
            /** Format: uuid */
            changedBy?: string;
            /** Format: date-time */
            changedAt?: string;
        };
        PublisherResponse: {
            /** Format: uuid */
            id?: string;
            name?: string;
        };
        PublicationPlaceResponse: {
            /** Format: uuid */
            id?: string;
            name?: string;
        };
        ImageRegionResponse: {
            /** Format: uuid */
            id?: string;
            /** Format: double */
            x?: number;
            /** Format: double */
            y?: number;
            /** Format: double */
            width?: number;
            /** Format: double */
            height?: number;
            extractedText?: string;
        };
        PageResponse: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            bookId?: string;
            /** Format: uuid */
            chapterId?: string;
            /** Format: int32 */
            pageNumber?: number;
            printedPage?: string;
            part?: string;
            /** Format: int32 */
            pdfPageNumber?: number;
            textContent?: string;
            imageUrl?: string;
            imageRegions?: components["schemas"]["ImageRegionResponse"][];
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        MuhaqqiqResponse: {
            /** Format: uuid */
            id?: string;
            name?: string;
            fullName?: string;
        };
        BookSummaryResponse: {
            /** Format: uuid */
            id?: string;
            /** @enum {string} */
            bookType?: "QURAN" | "HADITH_COLLECTION" | "BOOK" | "ARTICLE" | "MANUSCRIPT";
            title?: string;
            /** Format: uuid */
            authorityId?: string;
            language?: string;
            /** Format: date-time */
            createdAt?: string;
        };
        StreamingResponseBody: Record<string, never>;
        PdfFileInfoResponse: {
            /** Format: int32 */
            index?: number;
            label?: string;
            isCover?: boolean;
            /** Format: int64 */
            sizeBytes?: number;
            /** Format: int32 */
            pageCount?: number;
        };
        PdfInfoResponse: {
            hasCover?: boolean;
            /** Format: int64 */
            totalSizeBytes?: number;
            files?: components["schemas"]["PdfFileInfoResponse"][];
        };
        PageSummaryResponse: {
            /** Format: uuid */
            id?: string;
            /** Format: int32 */
            pageNumber?: number;
            printedPage?: string;
            part?: string;
            /** Format: uuid */
            chapterId?: string;
            hasText?: boolean;
            hasImage?: boolean;
        };
        SyncStatusResponse: {
            /** Format: int32 */
            masterVersion?: number;
            /** Format: date-time */
            lastSyncedAt?: string;
            /** Format: int32 */
            categoriesCount?: number;
            /** Format: int32 */
            authorsCount?: number;
            /** Format: int32 */
            booksCount?: number;
            /** Format: int32 */
            mappedBooksCount?: number;
        };
        StagingBookSearchResponse: {
            /** Format: int64 */
            bookId?: number;
            name?: string;
            authorName?: string;
            /** Format: int32 */
            majorRelease?: number;
            isMapped?: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TopicResponse"][];
                };
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header: {
                /** @description UUID текущего пользователя (ADR-006, временно до Spring Security в Этапе 6) */
                "X-User-Id": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTopicRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TopicResponse"];
                };
            };
        };
    };
    importMultipart: {
        parameters: {
            query: {
                currentUserId: string;
            };
            header: {
                /** @description UUID текущего пользователя (ADR-006, временно до Spring Security в Этапе 6) */
                "X-User-Id": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                    /** Format: uuid */
                    currentUserId?: string;
                };
                "application/json": components["schemas"]["TopicExportDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TopicImportResponse"];
                };
            };
        };
    };
    list_1: {
        parameters: {
            query?: {
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SourceResponse"][];
                };
            };
        };
    };
    create_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSourceRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SourceResponse"];
                };
            };
        };
    };
    list_2: {
        parameters: {
            query?: {
                status?: "OPEN" | "ANSWERED" | "CLOSED";
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["QuestionResponse"][];
                };
            };
        };
    };
    create_2: {
        parameters: {
            query: {
                currentUserId: string;
            };
            header: {
                /** @description UUID текущего пользователя (ADR-006, временно до Spring Security в Этапе 6) */
                "X-User-Id": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateQuestionRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["QuestionResponse"];
                };
            };
        };
    };
    create_3: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                questionId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CitationRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["QuestionSourceResponse"];
                };
            };
        };
    };
    list_3: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                questionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AnswerResponse"][];
                };
            };
        };
    };
    create_4: {
        parameters: {
            query: {
                currentUserId: string;
            };
            header: {
                /** @description UUID текущего пользователя (ADR-006, временно до Spring Security в Этапе 6) */
                "X-User-Id": string;
            };
            path: {
                questionId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAnswerRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AnswerResponse"];
                };
            };
        };
    };
    acceptAnswer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                questionId: string;
                answerId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["QuestionResponse"];
                };
            };
        };
    };
    create_5: {
        parameters: {
            query?: never;
            header: {
                /** @description UUID текущего пользователя (ADR-006, временно до Spring Security в Этапе 6) */
                "X-User-Id": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateNodeRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["NodeResponse"];
                };
            };
        };
    };
    list_4: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                nodeId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["NodeSourceResponse"][];
                };
            };
        };
    };
    attach: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                nodeId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AttachSourceRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["NodeSourceResponse"];
                };
            };
        };
    };
    create_6: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                nodeId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CitationRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["NodeSourceResponse"];
                };
            };
        };
    };
    uploadFile: {
        parameters: {
            query?: {
                title?: string;
                authorityId?: string;
                language?: string;
                description?: string;
                muhaqqiqName?: string;
                publisherName?: string;
                publicationPlaceName?: string;
                editionNumber?: number;
                publishedYearHijri?: number;
                publishedYearGregorian?: number;
            };
            header: {
                /** @description UUID текущего пользователя (ADR-006, временно до Spring Security в Этапе 6) */
                "X-User-Id": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                    /** Format: uuid */
                    currentUserId?: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileImportResponse"];
                };
            };
        };
    };
    list_5: {
        parameters: {
            query?: {
                q?: string;
                type?: "QURAN" | "HADITH_COLLECTION" | "BOOK" | "ARTICLE" | "MANUSCRIPT";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BookSummaryResponse"][];
                };
            };
        };
    };
    create_7: {
        parameters: {
            query: {
                currentUserId: string;
            };
            header: {
                /** @description UUID текущего пользователя (ADR-006, временно до Spring Security в Этапе 6) */
                "X-User-Id": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateBookRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BookResponse"];
                };
            };
        };
    };
    create_8: {
        parameters: {
            query?: never;
            header: {
                /** @description UUID текущего пользователя (ADR-006, временно до Spring Security в Этапе 6) */
                "X-User-Id": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateEdgeRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["EdgeResponse"];
                };
            };
        };
    };
    list_6: {
        parameters: {
            query?: {
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AuthorityResponse"][];
                };
            };
        };
    };
    create_9: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAuthorityRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AuthorityResponse"];
                };
            };
        };
    };
    create_10: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                answerId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CitationRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AnswerSourceResponse"];
                };
            };
        };
    };
    syncMaster: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SyncMasterResponse"];
                };
            };
        };
    };
    mapBook: {
        parameters: {
            query: {
                currentUserId: string;
            };
            header: {
                /** @description UUID текущего пользователя (ADR-006, временно до Spring Security в Этапе 6) */
                "X-User-Id": string;
            };
            path: {
                bookId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MapBookResponse"];
                };
            };
        };
    };
    importBook: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bookId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ImportBookResponse"];
                };
            };
        };
    };
    backfillBibliography: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BackfillBibliographyResponse"];
                };
            };
        };
    };
    getOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                questionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["QuestionResponse"];
                };
            };
        };
    };
    delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                questionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                questionId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateQuestionRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["QuestionResponse"];
                };
            };
        };
    };
    delete_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                nodeId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update_1: {
        parameters: {
            query?: never;
            header: {
                /** @description UUID текущего пользователя (ADR-006, временно до Spring Security в Этапе 6) */
                "X-User-Id": string;
            };
            path: {
                nodeId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateNodeRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["NodeResponse"];
                };
            };
        };
    };
    getOne_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bookId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BookDetailResponse"];
                };
            };
        };
    };
    delete_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bookId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bookId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateBookRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BookDetailResponse"];
                };
            };
        };
    };
    delete_3: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                edgeId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update_3: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                edgeId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateEdgeRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["EdgeResponse"];
                };
            };
        };
    };
    delete_4: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                answerId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update_4: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                answerId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateAnswerRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AnswerResponse"];
                };
            };
        };
    };
    getOne_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                topicId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TopicResponse"];
                };
            };
        };
    };
    delete_5: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                topicId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getGraph: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                topicId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["GraphResponse"];
                };
            };
        };
    };
    export: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                topicId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TopicExportDto"];
                };
            };
        };
    };
    getOne_3: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sourceId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SourceResponse"];
                };
            };
        };
    };
    delete_6: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sourceId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_7: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                questionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["QuestionSourceResponse"][];
                };
            };
        };
    };
    getRevisions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                nodeId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RevisionResponse"][];
                };
            };
        };
    };
    search: {
        parameters: {
            query?: {
                q?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PublisherResponse"][];
                };
            };
        };
    };
    search_1: {
        parameters: {
            query?: {
                q?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PublicationPlaceResponse"][];
                };
            };
        };
    };
    getPage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pageId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageResponse"];
                };
            };
        };
    };
    search_2: {
        parameters: {
            query?: {
                q?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MuhaqqiqResponse"][];
                };
            };
        };
    };
    streamPdf: {
        parameters: {
            query?: {
                fileIndex?: number;
            };
            header?: {
                Range?: string;
            };
            path: {
                bookId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["StreamingResponseBody"];
                };
            };
        };
    };
    getPdfInfo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bookId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PdfInfoResponse"];
                };
            };
        };
    };
    listPages: {
        parameters: {
            query?: {
                from?: number;
                to?: number;
            };
            header?: never;
            path: {
                bookId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageSummaryResponse"][];
                };
            };
        };
    };
    getOne_4: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                authorityId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AuthorityResponse"];
                };
            };
        };
    };
    delete_7: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                authorityId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_8: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                answerId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AnswerSourceResponse"][];
                };
            };
        };
    };
    syncStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SyncStatusResponse"];
                };
            };
        };
    };
    searchBooks: {
        parameters: {
            query: {
                q: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["StagingBookSearchResponse"][];
                };
            };
        };
    };
    detach: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                questionId: string;
                questionSourceId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    revokeAcceptance: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                questionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["QuestionResponse"];
                };
            };
        };
    };
    detach_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                nodeId: string;
                nodeSourceId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    detach_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                answerId: string;
                answerSourceId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
